/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app-sidebar/AppSidebar.vue')['default']
    BranchCard: typeof import('./src/components/branch/BranchCard.vue')['default']
    BranchSelectionModal: typeof import('./src/components/branch/BranchSelectionModal.vue')['default']
    BranchSelector: typeof import('./src/components/app-header/BranchSelector.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CartButton: typeof import('./src/components/cart/CartButton.vue')['default']
    CartDialog: typeof import('./src/components/cart/CartDialog.vue')['default']
    CartItem: typeof import('./src/components/cart/CartItem.vue')['default']
    CartStep: typeof import('./src/components/cart/CartStep.vue')['default']
    CategoryNavigationCard: typeof import('./src/components/category/categoryNavigationCard.vue')['default']
    CategoryNavigationDesktop: typeof import('./src/components/category/CategoryNavigationDesktop.vue')['default']
    CategoryNavigationItem: typeof import('./src/components/category/CategoryNavigationItem.vue')['default']
    CommonCounter: typeof import('./src/components/common/CommonCounter.vue')['default']
    CommonCounterCenter: typeof import('./src/components/common/CommonCounterCenter.vue')['default']
    CommonCounterLarge: typeof import('./src/components/common/CommonCounterLarge.vue')['default']
    CommonCounterRight: typeof import('./src/components/common/CommonCounterRight.vue')['default']
    Counter: typeof import('./src/components/common/Counter.vue')['default']
    CratModal: typeof import('./src/components/cart/CratModal.vue')['default']
    DesktopCart: typeof import('./src/components/cart/DesktopCart.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    OrderConfirmStep: typeof import('./src/components/order/OrderConfirmStep.vue')['default']
    OrderCreatedStep: typeof import('./src/components/order/OrderCreatedStep.vue')['default']
    OrderDialog: typeof import('./src/components/order/OrderDialog.vue')['default']
    OrderDialogHeader: typeof import('./src/components/order/OrderDialogHeader.vue')['default']
    OrderFormStep: typeof import('./src/components/order/OrderFormStep.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductSection: typeof import('./src/components/product/ProductSection.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarSettings: typeof import('./src/components/app-sidebar/SidebarSettings.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonProductCard: typeof import('./src/components/product/SkeletonProductCard.vue')['default']
    StateSetting: typeof import('./src/components/state/StateSetting.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
