/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '1)': typeof import('./src/components/order/order-step/OrderConfirmStep (copy 1).vue')['default']
    AppFooter: typeof import('./src/components/app-footer/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/app-header/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app-sidebar/AppSidebar.vue')['default']
    BranchCard: typeof import('./src/components/branch/BranchCard.vue')['default']
    BranchSelectionModal: typeof import('./src/components/branch/BranchSelectionModal.vue')['default']
    BranchSelector: typeof import('./src/components/app-header/BranchSelector.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CartButton: typeof import('./src/components/cart/CartButton.vue')['default']
    CartDialog: typeof import('./src/components/cart/CartDialog.vue')['default']
    CartItem: typeof import('./src/components/cart/CartItem.vue')['default']
    CartStep: typeof import('./src/components/order/order-step/CartStep.vue')['default']
    CategoryNavigationCard: typeof import('./src/components/category/categoryNavigationCard.vue')['default']
    CategoryNavigationDesktop: typeof import('./src/components/category/CategoryNavigationDesktop.vue')['default']
    CategoryNavigationItem: typeof import('./src/components/category/CategoryNavigationItem.vue')['default']
    CategoryNavigationMobile: typeof import('./src/components/category/CategoryNavigationMobile.vue')['default']
    CommonCounter: typeof import('./src/components/common/CommonCounter.vue')['default']
    CommonCounterCenter: typeof import('./src/components/common/CommonCounterCenter.vue')['default']
    CommonCounterLarge: typeof import('./src/components/common/CommonCounterLarge.vue')['default']
    CommonCounterRight: typeof import('./src/components/common/CommonCounterRight.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Counter: typeof import('./src/components/common/Counter.vue')['default']
    CounterCenter: typeof import('./src/components/common/CounterCenter.vue')['default']
    CratModal: typeof import('./src/components/cart/CratModal.vue')['default']
    DesktopCart: typeof import('./src/components/cart/DesktopCart.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FooterComp: typeof import('./src/components/app-footer/FooterComp.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OrderCloseButton: typeof import('./src/components/order/order-dialog/OrderCloseButton.vue')['default']
    OrderConfirmStep: typeof import('./src/components/order/order-step/OrderConfirmStep.vue')['default']
    OrderCreatedStep: typeof import('./src/components/order/order-step/OrderCreatedStep.vue')['default']
    OrderDialog: typeof import('./src/components/order/OrderDialog.vue')['default']
    OrderDialogFooter: typeof import('./src/components/order/order-dialog/OrderDialogFooter.vue')['default']
    OrderDialogHeader: typeof import('./src/components/order/order-dialog/OrderDialogHeader.vue')['default']
    OrderDialogSteps: typeof import('./src/components/order/order-dialog/OrderDialogSteps.vue')['default']
    OrderFooter: typeof import('./src/components/order/order-dialog/OrderFooter.vue')['default']
    OrderFormStep: typeof import('./src/components/order/order-step/OrderFormStep.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductSection: typeof import('./src/components/product/ProductSection.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarSettings: typeof import('./src/components/app-sidebar/SidebarSettings.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonProductCard: typeof import('./src/components/product/SkeletonProductCard.vue')['default']
    StateSetting: typeof import('./src/components/state/StateSetting.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
