/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app-sidebar/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarSettings: typeof import('./src/components/app-sidebar/SidebarSettings.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonProductCard: typeof import('./src/components/product/SkeletonProductCard.vue')['default']
    StateSetting: typeof import('./src/components/state/StateSetting.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
