ARG ELIXIR_VERSION=1.17.3
ARG OTP_VERSION=27.3.4.18
ARG DEBIAN_VERSION=bookworm-20260918-slim

ARG BUILDER_IMAGE="docker.io/hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="docker.io/debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS backend-builder
WORKDIR /app/server

RUN apt-get update && apt-get install -y build-essential git curl && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs

ENV MIX_ENV=prod

RUN mix local.hex --force && mix local.rebar --force

COPY server/mix.exs server/mix.lock ./
RUN mix deps.get --only prod
RUN mix deps.compile

COPY server/assets assets
RUN cd assets && npm install

COPY server/priv priv
COPY server/lib lib
COPY server/config config

RUN mix compile
RUN mix assets.deploy
RUN mix phx.digest
RUN mix release

FROM ${RUNNER_IMAGE}
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libstdc++6 openssl libncurses5 locales ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i '/en_US.UTF-8/s/^# //' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:C.UTF-8 LC_ALL=en_US.UTF-8 \
    MIX_ENV=prod

COPY --from=backend-builder /app/server/_build/prod/rel/delivest ./

EXPOSE 4000
ENV PORT=4000

CMD ["bin/delivest", "start"]