// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/04/2026, 18:01:07
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/kirill/storage/site/delivest/apps/delivest-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/plugins/**/*.{js,ts,mjs}","/home/kirill/storage/site/delivest/apps/delivest-web/composables/**/*.{js,ts,mjs}","/home/kirill/storage/site/delivest/apps/delivest-web/utils/**/*.{js,ts,mjs}","/home/kirill/storage/site/delivest/apps/delivest-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kirill/storage/site/delivest/apps/delivest-web/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;